spring.application.name=expertListing

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/expertlisting}
spring.datasource.username=${DB_USERNAME:expertlisting_user}
spring.datasource.password=${DB_PASSWORD:expertlisting_pass}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# JWT Configuration
app.jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXZlcnktc2VjdXJlLWtleS10aGF0LW11c3QtYmUtYXQtbGVhc3QtMjU2LWJpdHMtbG9uZw==}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:2592000000}
